export const START_GAME = 'START_GAME';
export const GAME_OVER = 'GAME_OVER';

export const SET_BEST_SCORE = 'SET_BEST_SCORE';
export const SET_BEST_SCORE_TO_DB_START = 'SET_BEST_SCORE_TO_DB_START';
export const SET_BEST_SCORE_TO_DB_SUCCESS = 'SET_BEST_SCORE_TO_DB_SUCCESS';
export const SET_BEST_SCORE_TO_DB_FAILURE = 'SET_BEST_SCORE_TO_DB_FAILURE';

export const GET_BEST_SCORE_FROM_DB_START = 'GET_BEST_SCORE_FROM_DB_START';
export const GET_BEST_SCORE_FROM_DB_SUCCESS = 'GET_BEST_SCORE_FROM_DB_SUCCESS';
export const GET_BEST_SCORE_FROM_DB_FAILURE = 'GET_BEST_SCORE_FROM_DB_FAILURE';

export const SET_SCORE = 'SET_SCORE';

export const TAP_HAPPENED = 'TAP_HAPPENED';
export const TAP_HANDLED = 'TAP_HANDLED';