const gameActionTypes = {
	START_GAME: 'START_GAME',
	GAME_OVER: 'GAME_OVER',
	SET_FINAL_SCORE: 'SET_FINAL_SCORE',
	TAP_HAPPENED: 'TAP_HAPPENED',
	TAP_HANDLED: 'TAP_HANDLED',
}

export default gameActionTypes;